import 'package:contract_driven_interface_generation/contract_driven_interface_generation.dart';
import 'package:path/path.dart' as p;

import 'model_catalog.dart';
import 'name_utils.dart';

String _fieldDartType(
  Map<String, dynamic> prop,
  bool required,
  Set<String> catalogNames,
) {
  final ref = prop[r'$ref'];
  if (ref is String) {
    final name = parseLocalSchemaRef(ref);
    if (name != null && catalogNames.contains(name)) {
      final dart = toPascal(refToDartName(name));
      return required ? dart : '$dart?';
    }
    return required ? 'Map<String, dynamic>' : 'Map<String, dynamic>?';
  }
  final items = prop['items'];
  if (prop['type']?.toString() == 'array' && items is Map) {
    final im = items is Map<String, dynamic> ? items : Map<String, dynamic>.from(items);
    final ir = im[r'$ref'];
    if (ir is String) {
      final name = parseLocalSchemaRef(ir);
      if (name != null && catalogNames.contains(name)) {
        final dart = toPascal(refToDartName(name));
        final inner = 'List<$dart>';
        return required ? inner : '$inner?';
      }
    }
    final inline = im['type']?.toString();
    if (inline == 'string') {
      return required ? 'List<String>' : 'List<String>?';
    }
    if (inline == 'integer') {
      return required ? 'List<int>' : 'List<int>?';
    }
    return required ? 'List<dynamic>' : 'List<dynamic>?';
  }
  switch (prop['type']?.toString()) {
    case 'string':
      return required ? 'String' : 'String?';
    case 'integer':
      return required ? 'int' : 'int?';
    case 'number':
      return required ? 'double' : 'double?';
    case 'boolean':
      return required ? 'bool' : 'bool?';
    case 'object':
      return required ? 'Map<String, dynamic>' : 'Map<String, dynamic>?';
    default:
      return required ? 'dynamic' : 'dynamic?';
  }
}

List<String> _collectDepImports(
  String schemaName,
  Map<String, dynamic> schema,
  ModelKind currentKind,
  Map<String, ModelKind> kinds,
  Set<String> catalogNames,
  String dtoDir,
  String voDir,
) {
  final fromSub = modelSubdir(currentKind, dtoDir, voDir);
  final imports = <String>{};
  final props = schema['properties'];
  if (props is! Map) {
    return [];
  }
  for (final v in props.values) {
    if (v is! Map) {
      continue;
    }
    final m = v is Map<String, dynamic> ? v : Map<String, dynamic>.from(v);
    void addRef(String? refStr) {
      final name = refStr != null ? parseLocalSchemaRef(refStr) : null;
      if (name == null || !catalogNames.contains(name) || name == schemaName) {
        return;
      }
      final k = kinds[name] ?? ModelKind.vo;
      final toSub = modelSubdir(k, dtoDir, voDir);
      final file = '${toSnake(refToDartName(name))}.dart';
      final rel = p.relative(p.join(toSub, file), from: fromSub).replaceAll(r'\', '/');
      imports.add(rel);
    }

    addRef(m[r'$ref'] as String?);
    final items = m['items'];
    if (items is Map) {
      final im = items is Map<String, dynamic> ? items : Map<String, dynamic>.from(items);
      addRef(im[r'$ref'] as String?);
    }
  }
  final list = imports.toList()..sort();
  return list;
}

String renderModelDartFile({
  required String schemaName,
  required Map<String, dynamic> schema,
  required ModelKind kind,
  required Map<String, ModelKind> kinds,
  required Set<String> catalogNames,
  required String dtoDir,
  required String voDir,
}) {
  final dartName = refToDartName(schemaName);
  final className = toPascal(dartName);
  final fileBase = toSnake(dartName);

  final req = <String>{};
  final rq = schema['required'];
  if (rq is List) {
    for (final e in rq) {
      req.add(e.toString());
    }
  }

  final props = schema['properties'];
  final propNames = <String>[];
  if (props is Map) {
    propNames.addAll(props.keys.map((e) => e.toString()).toList()..sort());
  }

  final imports = _collectDepImports(
    schemaName,
    schema,
    kind,
    kinds,
    catalogNames,
    dtoDir,
    voDir,
  );

  final buf = StringBuffer()
    ..writeln('// Code generated by contract_driven_interface_generation_net_retrofit. DO NOT EDIT.')
    ..writeln()
    ..writeln("import 'package:json_annotation/json_annotation.dart';");
  for (final imp in imports) {
    buf.writeln("import '$imp';");
  }
  buf
    ..writeln()
    ..writeln("part '$fileBase.g.dart';")
    ..writeln();
  final desc = schema['description']?.toString().trim();
  if (desc != null && desc.isNotEmpty) {
    buf.writeln('/// $desc');
  }
  buf.writeln('@JsonSerializable()');
  buf.writeln('class $className {');

  final fields = <({String dartName, String type, String jsonKey, bool isRequired, String? desc})>[];
  for (final key in propNames) {
    final raw = props![key];
    if (raw is! Map) {
      continue;
    }
    final pm = raw is Map<String, dynamic> ? raw : Map<String, dynamic>.from(raw);
    final isReq = req.contains(key);
    final dn = jsonKeyToDartName(key);
    final typ = _fieldDartType(pm, isReq, catalogNames);
    final pDesc = pm['description']?.toString().trim();
    fields.add((
      dartName: dn,
      type: typ,
      jsonKey: key,
      isRequired: isReq,
      desc: pDesc != null && pDesc.isNotEmpty ? pDesc : null,
    ));
  }

  for (final f in fields) {
    if (f.desc != null) {
      buf.writeln('  /// ${f.desc}');
    }
    final needKey = f.jsonKey != f.dartName;
    if (needKey) {
      final escaped = f.jsonKey.replaceAll(r'\', r'\\').replaceAll('"', r'\"');
      buf.writeln('  @JsonKey(name: "$escaped")');
    }
    buf.writeln('  final ${f.type} ${f.dartName};');
  }

  buf.writeln();
  if (fields.isEmpty) {
    buf.writeln('  $className();');
  } else {
    buf.writeln('  $className({');
    for (final f in fields) {
      buf.writeln(
        f.isRequired ? '    required this.${f.dartName},' : '    this.${f.dartName},',
      );
    }
    buf.writeln('  });');
  }
  buf
    ..writeln()
    ..writeln('  factory $className.fromJson(Map<String, dynamic> json) =>')
    ..writeln('      _\$${className}FromJson(json);')
    ..writeln('  Map<String, dynamic> toJson() => _\$${className}ToJson(this);')
    ..writeln('}');
  return buf.toString();
}
