import 'package:path/path.dart' as p;

import 'codegen_operation.dart';
import 'model_catalog.dart';
import 'name_utils.dart';

String _pathConstExpr(
    String apiClass, String path, Map<String, String> pathConstNames) {
  final name = pathConstNames[path];
  if (name != null && name.isNotEmpty) {
    return '$apiClass.$name';
  }
  return "'$path'";
}

List<String> _errorDocLines(CodegenOperation co) {
  final op = co.source;
  final out = <String>[];
  const success = {'200', '201', '202'};
  final codes = op.responsesByCode.keys
      .where((c) => !success.contains(c))
      .toList()
    ..sort();
  for (final code in codes) {
    final r = op.responsesByCode[code];
    final desc = r?.description?.trim() ?? '';
    if (desc.isNotEmpty) {
      out.add('$code $desc');
    } else {
      out.add(code);
    }
  }
  return out;
}

/// `{prefix}_interfaces.dart`：`@NetApi` + 抽象方法（`part` 由 `build_runner` 生成 `.g.dart`）。
String renderInterfaceDartFile({
  required String prefix,
  required List<CodegenOperation> codegenOps,
  required Map<String, String> pathConstNames,
  required String apisDir,
  required String interfacesDir,
  required String dtoDir,
  required String voDir,
  required ModelCatalog catalog,
  String? netApiClient,
}) {
  final apiClass = '${toPascal(prefix)}Api';
  final serverClass = '${toPascal(prefix)}Server';
  final fileBase = '${prefix}_interfaces';

  var needDio = false;
  var needConvert = false;
  var needIo = false;
  for (final co in codegenOps) {
    if (co.streamResponse) {
      needDio = true;
      needConvert = true;
    }
    if (co.formData) {
      needDio = true;
      for (final fp in co.formParts) {
        if (fp.isFile) {
          needIo = true;
          break;
        }
      }
    }
  }

  final imports = <String>{
    'package:net_retrofit_dio/net_retrofit_dio.dart',
  };
  if (needDio) {
    imports.add('package:dio/dio.dart');
  }
  if (needConvert) {
    imports.add('dart:convert');
  }
  if (needIo) {
    imports.add('dart:io');
  }

  final apiRel = p
      .relative(
        p.join(apisDir, '${prefix}_api.dart'),
        from: interfacesDir,
      )
      .replaceAll(r'\', '/');
  imports.add(apiRel);

  final modelRefs = <String>{};
  for (final co in codegenOps) {
    final b = co.requestBodyRef?.trim();
    if (b != null && catalog.kinds.containsKey(b)) {
      modelRefs.add(b);
    }
    final r = co.responseRefForImport?.trim();
    if (r != null && catalog.kinds.containsKey(r)) {
      modelRefs.add(r);
    }
  }
  for (final name in modelRefs.toList()..sort()) {
    final k = catalog.kinds[name] ?? ModelKind.vo;
    final sub = modelSubdir(k, dtoDir, voDir);
    final file = '${toSnake(refToDartName(name))}.dart';
    final rel = p
        .relative(p.join(sub, file), from: interfacesDir)
        .replaceAll(r'\', '/');
    imports.add(rel);
  }

  final sortedImports = imports.toList()
    ..sort((a, b) {
      int bucket(String s) {
        if (s.startsWith('dart:')) {
          return 0;
        }
        if (s.startsWith('package:')) {
          return 1;
        }
        return 2;
      }

      final ba = bucket(a);
      final bb = bucket(b);
      if (ba != bb) {
        return ba.compareTo(bb);
      }
      return a.compareTo(b);
    });

  final buf = StringBuffer()
    ..writeln(
        '// Code generated by contract_driven_interface_generation_net_retrofit. DO NOT EDIT.')
    ..writeln();
  for (final imp in sortedImports) {
    buf.writeln("import '$imp';");
  }
  buf
    ..writeln()
    ..writeln("part '$fileBase.g.dart';")
    ..writeln();
  final client = netApiClient?.trim();
  if (client != null && client.isNotEmpty) {
    buf.writeln("@NetApi(client: '$client')");
  } else {
    buf.writeln('@NetApi()');
  }
  buf.writeln('abstract class $serverClass {');

  for (final co in codegenOps) {
    final op = co.source;
    if (op.summary?.trim().isNotEmpty == true) {
      buf.writeln('  /// ${op.summary!.trim()}');
    }
    final desc = op.description?.trim();
    if (desc != null && desc.isNotEmpty && desc != op.summary?.trim()) {
      for (final line in desc.split('\n')) {
        final t = line.trim();
        if (t.isNotEmpty) {
          buf.writeln('  /// $t');
        }
      }
    }
    final errs = _errorDocLines(co);
    if (errs.isNotEmpty) {
      buf.writeln('  /// 错误码: ${errs.join(', ')}');
    }

    final pathExpr = _pathConstExpr(apiClass, op.path, pathConstNames);
    if (co.formData) {
      buf.writeln(
          '  @${co.httpAnno}($pathExpr, contentType: ContentType.formData)');
    } else {
      buf.writeln('  @${co.httpAnno}($pathExpr)');
    }
    if (co.dataPath != null && co.dataPath!.isNotEmpty && !co.streamResponse) {
      buf.writeln("  @DataPath('${co.dataPath}')");
    }
    if (co.streamResponse) {
      buf.writeln('  @StreamResponse()');
    }

    final futureInner = co.returnType;
    buf.write('  Future<$futureInner> ${co.methodName}(');
    buf.write(co.paramDecls.join(', '));
    if (co.paramDecls.isNotEmpty) {
      buf.write(', ');
    }
    if (co.streamResponse) {
      buf.write('{CancelToken? cancelToken, CallOptions? options}');
    } else {
      buf.write('[CallOptions? options]');
    }
    buf.writeln(');\n');
  }

  buf.writeln('}');
  return buf.toString();
}
