import 'package:contract_driven_interface_generation/contract_driven_interface_generation.dart';

import 'name_utils.dart';

class _PathDoc {
  _PathDoc({required this.summary, required this.description});

  String summary;
  String description;
}

/// `{prefix}_api.dart`：路径常量类（与 Go `renderApiFile` 一致）。
String renderApiDartFile(String prefix, List<ParsedOperation> groupOps) {
  final byPath = <String, _PathDoc>{};
  for (final op in groupOps) {
    final path = op.path.trim();
    if (path.isEmpty) {
      continue;
    }
    final sum = op.summary?.trim() ?? '';
    final desc = op.description?.trim() ?? '';
    final existing = byPath[path];
    if (existing == null) {
      byPath[path] = _PathDoc(summary: sum, description: desc);
      continue;
    }
    if (existing.summary.isEmpty && sum.isNotEmpty) {
      existing.summary = sum;
    }
    if (existing.description.isEmpty && desc.isNotEmpty) {
      existing.description = desc;
    }
  }
  final paths = byPath.keys.toList()..sort();
  final constNames = _buildPathConstNames(paths);

  final apiClass = '${toPascal(prefix)}Api';
  final buf = StringBuffer()
    ..writeln('// Code generated by contract_driven_interface_generation_net_retrofit. DO NOT EDIT.')
    ..writeln()
    ..writeln('class $apiClass {');
  if (paths.isEmpty) {
    buf.writeln('}');
    return buf.toString();
  }
  for (final path in paths) {
    final ep = byPath[path]!;
    for (final line in _docLinesFromStrings(ep.summary, ep.description)) {
      buf.writeln('  /// $line');
    }
    buf.writeln("  static const String ${constNames[path]} = '$path';");
  }
  buf.writeln('}');
  return buf.toString();
}

List<String> _docLinesFromStrings(String summary, String description) {
  final lines = <String>[];
  final sum = summary.trim();
  final desc = description.trim();
  if (sum.isNotEmpty) {
    lines.add(sum);
  }
  if (desc.isNotEmpty && desc != sum) {
    for (final line in desc.split('\n')) {
      final t = line.trim();
      if (t.isNotEmpty) {
        lines.add(t);
      }
    }
  }
  return lines;
}

Map<String, String> _buildPathConstNames(List<String> paths) {
  final out = <String, String>{};
  final counts = <String, int>{};
  for (final path in paths) {
    final base = pathToConstName(path);
    final n = (counts[base] ?? 0) + 1;
    counts[base] = n;
    out[path] = n > 1 ? '$base$n' : base;
  }
  return out;
}

/// path → const 名（供 interface 生成 URL 表达式）。
Map<String, String> pathConstNamesForGroup(List<ParsedOperation> groupOps) {
  final byPath = <String, void>{};
  for (final op in groupOps) {
    final path = op.path.trim();
    if (path.isNotEmpty) {
      byPath[path] = null;
    }
  }
  final paths = byPath.keys.toList()..sort();
  return _buildPathConstNames(paths);
}
